all: main1 main2
main1: main.cpp Database.cpp SQL.cpp sql_server.cpp Table.cpp Database.h Header.h SQL.h sql_server.h Table.h
	g++ -std=c++14 -o main1 main.cpp Database.cpp Table.cpp sql_server.cpp SQL.cpp
main2: main.cpp Database.cpp SQL.cpp sql_server.cpp Table.cpp Database.h Header.h SQL.h sql_server.h Table.h
	g++ -std=c++14 -o main2 main.cpp Database.cpp Table.cpp sql_server.cpp SQL.cpp